/**
 * The model registry data. GENERATED - edited by scripts/sync-models.mjs,
 * which rewrites this file from the daily price sync. Hand edits are kept:
 * the sync reads this file, changes only prices, limits and new rows, and
 * writes every other field back as it found it. See scripts/modelSync.ts.
 */

import type { Model } from './models.ts';

export const PRICING_AS_OF = '2026-09-26';

export const MODEL_DATA: Model[] = [
  // ----------------------------------------------------------- Anthropic
  {
    id: "claude-fable-5-1",
    apiId: "claude-fable-5-1",
    label: "Claude Fable 5.1",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 10,
    outputPerM: 50,
    cacheReadPerM: 0.25,
    cacheWritePerM: 12.5,
    batchDiscount: 0.5,
    note: "Cache reads are a flat $0.25/MTok (0.025x input) rather than the usual 0.1x.",
  },
  {
    id: "claude-fable-5",
    apiId: "claude-fable-5",
    label: "Claude Fable 5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 10,
    outputPerM: 50,
    cacheReadPerM: 1,
    cacheWritePerM: 12.5,
    batchDiscount: 0.5,
  },
  {
    id: "claude-opus-5",
    apiId: "claude-opus-5",
    label: "Claude Opus 5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 5,
    outputPerM: 25,
    cacheReadPerM: 0.5,
    cacheWritePerM: 6.25,
    batchDiscount: 0.5,
  },
  {
    id: "claude-opus-4-8",
    apiId: "claude-opus-4-8",
    label: "Claude Opus 4.8",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 5,
    outputPerM: 25,
    cacheReadPerM: 0.5,
    cacheWritePerM: 6.25,
    batchDiscount: 0.5,
  },
  {
    id: "claude-opus-4-7",
    apiId: "claude-opus-4-7",
    label: "Claude Opus 4.7",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 5,
    outputPerM: 25,
    cacheReadPerM: 0.5,
    cacheWritePerM: 6.25,
    batchDiscount: 0.5,
  },
  {
    id: "claude-sonnet-5",
    apiId: "claude-sonnet-5",
    label: "Claude Sonnet 5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 2,
    outputPerM: 10,
    cacheReadPerM: 0.2,
    cacheWritePerM: 2.5,
    batchDiscount: 0.5,
  },
  {
    id: "claude-sonnet-4-6",
    apiId: "claude-sonnet-4-6",
    label: "Claude Sonnet 4.6",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 3,
    outputPerM: 15,
    cacheReadPerM: 0.3,
    cacheWritePerM: 3.75,
    batchDiscount: 0.5,
  },
  {
    id: "claude-haiku-4-5",
    apiId: "claude-haiku-4-5",
    label: "Claude Haiku 4.5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 200_000,
    maxOutput: 64_000,
    inputPerM: 1,
    outputPerM: 5,
    cacheReadPerM: 0.1,
    cacheWritePerM: 1.25,
    batchDiscount: 0.5,
  },
  {
    id: "claude-mythos-5",
    apiId: "claude-mythos-5",
    label: "Claude Mythos 5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 10,
    outputPerM: 50,
    cacheReadPerM: 1,
    cacheWritePerM: 12.5,
    batchDiscount: 0.5,
  },
  {
    id: "claude-mythos-5-1",
    apiId: "claude-mythos-5-1",
    label: "Claude Mythos 5.1",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 10,
    outputPerM: 50,
    cacheReadPerM: 0.25,
    cacheWritePerM: 12.5,
    batchDiscount: 0.5,
  },
  {
    id: "claude-opus-4-5",
    apiId: "claude-opus-4-5",
    label: "Claude Opus 4.5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 200_000,
    maxOutput: 64_000,
    inputPerM: 5,
    outputPerM: 25,
    cacheReadPerM: 0.5,
    cacheWritePerM: 6.25,
    batchDiscount: 0.5,
  },
  {
    id: "claude-opus-4-6",
    apiId: "claude-opus-4-6",
    label: "Claude Opus 4.6",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 5,
    outputPerM: 25,
    cacheReadPerM: 0.5,
    cacheWritePerM: 6.25,
    batchDiscount: 0.5,
  },
  {
    id: "claude-opus-5-5",
    apiId: "claude-opus-5-5",
    label: "Claude Opus 5.5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 128_000,
    inputPerM: 4,
    outputPerM: 20,
    cacheReadPerM: 0.2,
    cacheWritePerM: 5,
    batchDiscount: 0.5,
  },
  {
    id: "claude-sonnet-4-5",
    apiId: "claude-sonnet-4-5",
    label: "Claude Sonnet 4.5",
    vendor: "Anthropic",
    tokenizer: "claude",
    context: 1_000_000,
    maxOutput: 64_000,
    inputPerM: 3,
    outputPerM: 15,
    cacheReadPerM: 0.3,
    cacheWritePerM: 3.75,
    batchDiscount: 0.5,
  },
  // -------------------------------------------------------------- OpenAI
  {
    id: "gpt-5",
    apiId: "gpt-5",
    label: "GPT-5",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 1.25,
    outputPerM: 10,
    cacheReadPerM: 0.125,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-mini",
    apiId: "gpt-5-mini",
    label: "GPT-5 mini",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 0.25,
    outputPerM: 2,
    cacheReadPerM: 0.025,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-nano",
    apiId: "gpt-5-nano",
    label: "GPT-5 nano",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 0.05,
    outputPerM: 0.4,
    cacheReadPerM: 0.005,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4-1",
    apiId: "gpt-4.1",
    label: "GPT-4.1",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 1_047_576,
    maxOutput: 32_768,
    inputPerM: 2,
    outputPerM: 8,
    cacheReadPerM: 0.5,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4-1-mini",
    apiId: "gpt-4.1-mini",
    label: "GPT-4.1 mini",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 1_047_576,
    maxOutput: 32_768,
    inputPerM: 0.4,
    outputPerM: 1.6,
    cacheReadPerM: 0.1,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4-1-nano",
    apiId: "gpt-4.1-nano",
    label: "GPT-4.1 nano",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 1_047_576,
    maxOutput: 32_768,
    inputPerM: 0.1,
    outputPerM: 0.4,
    cacheReadPerM: 0.025,
    batchDiscount: 0.5,
  },
  {
    id: "o3",
    apiId: "o3",
    label: "o3",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 200_000,
    maxOutput: 100_000,
    inputPerM: 2,
    outputPerM: 8,
    cacheReadPerM: 0.5,
    batchDiscount: 0.5,
  },
  {
    id: "o4-mini",
    apiId: "o4-mini",
    label: "o4-mini",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 200_000,
    maxOutput: 100_000,
    inputPerM: 1.1,
    outputPerM: 4.4,
    cacheReadPerM: 0.275,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4o",
    apiId: "gpt-4o",
    label: "GPT-4o",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 128_000,
    maxOutput: 16_384,
    inputPerM: 2.5,
    outputPerM: 10,
    cacheReadPerM: 1.25,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4o-mini",
    apiId: "gpt-4o-mini",
    label: "GPT-4o mini",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 128_000,
    maxOutput: 16_384,
    inputPerM: 0.15,
    outputPerM: 0.6,
    cacheReadPerM: 0.075,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4-turbo",
    apiId: "gpt-4-turbo",
    label: "GPT-4 Turbo",
    vendor: "OpenAI",
    tokenizer: "cl100k",
    context: 128_000,
    maxOutput: 4096,
    inputPerM: 10,
    outputPerM: 30,
    batchDiscount: 0.5,
    note: "Uses the older cl100k_base encoding, so the same text costs more tokens here.",
  },
  {
    id: "gpt-3-5-turbo",
    apiId: "gpt-3.5-turbo",
    label: "GPT-3.5 Turbo",
    vendor: "OpenAI",
    tokenizer: "cl100k",
    context: 16_385,
    maxOutput: 4096,
    inputPerM: 0.5,
    outputPerM: 1.5,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-4",
    apiId: "gpt-4",
    label: "GPT-4",
    vendor: "OpenAI",
    tokenizer: "cl100k",
    context: 8192,
    maxOutput: 4096,
    inputPerM: 30,
    outputPerM: 60,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-1",
    apiId: "gpt-5.1",
    label: "GPT-5.1",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 1.25,
    outputPerM: 10,
    cacheReadPerM: 0.125,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-2",
    apiId: "gpt-5.2",
    label: "GPT-5.2",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 1.75,
    outputPerM: 14,
    cacheReadPerM: 0.175,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-4",
    apiId: "gpt-5.4",
    label: "GPT-5.4",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 1_050_000,
    maxOutput: 128_000,
    inputPerM: 2.5,
    outputPerM: 15,
    cacheReadPerM: 0.25,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-4-mini",
    apiId: "gpt-5.4-mini",
    label: "GPT-5.4 mini",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 0.75,
    outputPerM: 4.5,
    cacheReadPerM: 0.075,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-4-nano",
    apiId: "gpt-5.4-nano",
    label: "GPT-5.4 nano",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 272_000,
    maxOutput: 128_000,
    inputPerM: 0.2,
    outputPerM: 1.25,
    cacheReadPerM: 0.02,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-5",
    apiId: "gpt-5.5",
    label: "GPT-5.5",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 1_050_000,
    maxOutput: 128_000,
    inputPerM: 5,
    outputPerM: 30,
    cacheReadPerM: 0.5,
    batchDiscount: 0.5,
  },
  {
    id: "gpt-5-6",
    apiId: "gpt-5.6",
    label: "GPT-5.6",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 922_000,
    maxOutput: 128_000,
    inputPerM: 4,
    outputPerM: 20,
    cacheReadPerM: 0.4,
    cacheWritePerM: 5,
    batchDiscount: 0.5,
  },
  {
    id: "o1",
    apiId: "o1",
    label: "o1",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 200_000,
    maxOutput: 100_000,
    inputPerM: 15,
    outputPerM: 60,
    cacheReadPerM: 7.5,
    batchDiscount: 0.5,
  },
  {
    id: "o3-mini",
    apiId: "o3-mini",
    label: "o3-mini",
    vendor: "OpenAI",
    tokenizer: "o200k",
    context: 200_000,
    maxOutput: 100_000,
    inputPerM: 1.1,
    outputPerM: 4.4,
    cacheReadPerM: 0.55,
    batchDiscount: 0.5,
  },
  // -------------------------------------------------------------- Google
  {
    id: "gemini-2-5-pro",
    apiId: "gemini-2.5-pro",
    label: "Gemini 2.5 Pro",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 1.25,
    outputPerM: 10,
    cacheReadPerM: 0.31,
    batchDiscount: 0.5,
    note: "Rate shown is the <=200K-token tier; prompts above 200K tokens bill at $2.50 / $15.",
  },
  {
    id: "gemini-2-5-flash",
    apiId: "gemini-2.5-flash",
    label: "Gemini 2.5 Flash",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.3,
    outputPerM: 2.5,
    cacheReadPerM: 0.075,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-2-5-flash-lite",
    apiId: "gemini-2.5-flash-lite",
    label: "Gemini 2.5 Flash-Lite",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.1,
    outputPerM: 0.4,
    cacheReadPerM: 0.025,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-1-flash-lite",
    apiId: "gemini-3.1-flash-lite",
    label: "Gemini 3.1 Flash-Lite",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.25,
    outputPerM: 1.5,
    cacheReadPerM: 0.025,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-1-flash-lite-preview",
    apiId: "gemini-3.1-flash-lite-preview",
    label: "Gemini 3.1 Flash-Lite (preview)",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.25,
    outputPerM: 1.5,
    cacheReadPerM: 0.025,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-1-pro-preview",
    apiId: "gemini-3.1-pro-preview",
    label: "Gemini 3.1 Pro (preview)",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 2,
    outputPerM: 12,
    cacheReadPerM: 0.2,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-5-flash",
    apiId: "gemini-3.5-flash",
    label: "Gemini 3.5 Flash",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 1.5,
    outputPerM: 9,
    cacheReadPerM: 0.15,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-5-flash-lite",
    apiId: "gemini-3.5-flash-lite",
    label: "Gemini 3.5 Flash-Lite",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.3,
    outputPerM: 2.5,
    cacheReadPerM: 0.03,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-6-flash",
    apiId: "gemini-3.6-flash",
    label: "Gemini 3.6 Flash",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.75,
    outputPerM: 3.75,
    cacheReadPerM: 0.075,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-7-flash",
    apiId: "gemini-3.7-flash",
    label: "Gemini 3.7 Flash",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.75,
    outputPerM: 3.75,
    cacheReadPerM: 0.075,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-8-flash",
    apiId: "gemini-3.8-flash",
    label: "Gemini 3.8 Flash",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.75,
    outputPerM: 3.75,
    cacheReadPerM: 0.075,
    batchDiscount: 0.5,
  },
  {
    id: "gemini-3-flash-preview",
    apiId: "gemini-3-flash-preview",
    label: "Gemini 3 Flash (preview)",
    vendor: "Google",
    tokenizer: "gemini",
    context: 1_048_576,
    maxOutput: 65_536,
    inputPerM: 0.5,
    outputPerM: 3,
    cacheReadPerM: 0.05,
    batchDiscount: 0.5,
  },
  // ----------------------------------------------------------------- xAI
  {
    id: "grok-4",
    apiId: "grok-4",
    label: "Grok 4",
    vendor: "xAI",
    tokenizer: "grok",
    context: 256_000,
    inputPerM: 3,
    outputPerM: 15,
    cacheReadPerM: 0.75,
  },
  {
    id: "grok-3-mini",
    apiId: "grok-3-mini",
    label: "Grok 3 mini",
    vendor: "xAI",
    tokenizer: "grok",
    context: 131_072,
    inputPerM: 0.3,
    outputPerM: 0.5,
  },
  {
    id: "grok-4-20",
    apiId: "grok-4.20",
    label: "Grok 4.20",
    vendor: "xAI",
    tokenizer: "grok",
    context: 1_000_000,
    maxOutput: 1_000_000,
    inputPerM: 1.25,
    outputPerM: 2.5,
    cacheReadPerM: 0.2,
  },
  {
    id: "grok-4-3",
    apiId: "grok-4.3",
    label: "Grok 4.3",
    vendor: "xAI",
    tokenizer: "grok",
    context: 1_000_000,
    maxOutput: 1_000_000,
    inputPerM: 1.25,
    outputPerM: 2.5,
    cacheReadPerM: 0.2,
  },
  {
    id: "grok-4-5",
    apiId: "grok-4.5",
    label: "Grok 4.5",
    vendor: "xAI",
    tokenizer: "grok",
    context: 500_000,
    maxOutput: 500_000,
    inputPerM: 2,
    outputPerM: 6,
    cacheReadPerM: 0.3,
  },
  {
    id: "grok-4-6",
    apiId: "grok-4.6",
    label: "Grok 4.6",
    vendor: "xAI",
    tokenizer: "grok",
    context: 500_000,
    maxOutput: 500_000,
    inputPerM: 2,
    outputPerM: 6,
    cacheReadPerM: 0.5,
  },
  {
    id: "grok-4-7",
    apiId: "grok-4.7",
    label: "Grok 4.7",
    vendor: "xAI",
    tokenizer: "grok",
    context: 500_000,
    maxOutput: 500_000,
    inputPerM: 2,
    outputPerM: 6,
    cacheReadPerM: 0.5,
  },
  // ------------------------------------------------------------ DeepSeek
  {
    id: "deepseek-v3",
    apiId: "deepseek-chat",
    label: "DeepSeek V3",
    vendor: "DeepSeek",
    tokenizer: "deepseek",
    context: 131_072,
    maxOutput: 8192,
    inputPerM: 0.28,
    outputPerM: 0.42,
    cacheReadPerM: 0.028,
  },
  {
    id: "deepseek-r1",
    apiId: "deepseek-reasoner",
    label: "DeepSeek R1",
    vendor: "DeepSeek",
    tokenizer: "deepseek",
    context: 131_072,
    maxOutput: 65_536,
    inputPerM: 0.28,
    outputPerM: 0.42,
    cacheReadPerM: 0.028,
  },
  {
    id: "deepseek-v3-2",
    apiId: "deepseek-v3.2",
    label: "DeepSeek V3.2",
    vendor: "DeepSeek",
    tokenizer: "deepseek",
    context: 163_840,
    maxOutput: 163_840,
    inputPerM: 0.28,
    outputPerM: 0.4,
    cacheReadPerM: 0.028,
  },
  {
    id: "deepseek-v4-flash",
    apiId: "deepseek-v4-flash",
    label: "DeepSeek V4 Flash",
    vendor: "DeepSeek",
    tokenizer: "deepseek",
    context: 1_000_000,
    maxOutput: 393_216,
    inputPerM: 0.3,
    outputPerM: 1.2,
    cacheReadPerM: 0.006,
  },
  {
    id: "deepseek-v4-pro",
    apiId: "deepseek-v4-pro",
    label: "DeepSeek V4 Pro",
    vendor: "DeepSeek",
    tokenizer: "deepseek",
    context: 1_000_000,
    maxOutput: 393_216,
    inputPerM: 1.32,
    outputPerM: 3.96,
    cacheReadPerM: 0.044,
  },
  // ------------------------------------------------------------- Mistral
  {
    id: "mistral-large-2",
    apiId: "mistral-large-latest",
    label: "Mistral Large 2",
    vendor: "Mistral",
    tokenizer: "mistral",
    context: 262_144,
    inputPerM: 0.5,
    outputPerM: 1.5,
    cacheReadPerM: 0.05,
    batchDiscount: 0.5,
  },
  {
    id: "mistral-small-3",
    apiId: "mistral-small-latest",
    label: "Mistral Small 3",
    vendor: "Mistral",
    tokenizer: "mistral",
    context: 262_144,
    inputPerM: 0.15,
    outputPerM: 0.6,
    cacheReadPerM: 0.015,
    batchDiscount: 0.5,
  },
  {
    id: "mistral-large-3",
    apiId: "mistral-large-3",
    label: "Mistral Large 3",
    vendor: "Mistral",
    tokenizer: "mistral",
    context: 262_144,
    maxOutput: 262_144,
    inputPerM: 0.5,
    outputPerM: 1.5,
    cacheReadPerM: 0.05,
    batchDiscount: 0.5,
  },
  {
    id: "mistral-medium-3",
    apiId: "mistral-medium-3",
    label: "Mistral Medium 3",
    vendor: "Mistral",
    tokenizer: "mistral",
    context: 262_144,
    maxOutput: 262_144,
    inputPerM: 1.5,
    outputPerM: 7.5,
    cacheReadPerM: 0.15,
    batchDiscount: 0.5,
  },
  {
    id: "mistral-medium-3-5",
    apiId: "mistral-medium-3-5",
    label: "Mistral Medium 3.5",
    vendor: "Mistral",
    tokenizer: "mistral",
    context: 262_144,
    maxOutput: 262_144,
    inputPerM: 1.5,
    outputPerM: 7.5,
    cacheReadPerM: 0.15,
    batchDiscount: 0.5,
  },
  // ---------------------------------------------------------------- Meta
  {
    id: "llama-4-maverick",
    apiId: "llama-4-maverick-17b-128e-instruct",
    label: "Llama 4 Maverick",
    vendor: "Meta",
    tokenizer: "llama",
    context: 1_048_576,
    inputPerM: 0.27,
    outputPerM: 0.85,
    hostedRate: true,
  },
  {
    id: "llama-4-scout",
    apiId: "llama-4-scout-17b-16e-instruct",
    label: "Llama 4 Scout",
    vendor: "Meta",
    tokenizer: "llama",
    context: 327_680,
    inputPerM: 0.18,
    outputPerM: 0.59,
    hostedRate: true,
  },
  {
    id: "llama-3-3-70b",
    apiId: "llama-3.3-70b-instruct",
    label: "Llama 3.3 70B",
    vendor: "Meta",
    tokenizer: "llama",
    context: 131_072,
    inputPerM: 0.88,
    outputPerM: 0.88,
    hostedRate: true,
  },
  // -------------------------------------------------------------- Cohere
  {
    id: "command-a",
    apiId: "command-a-03-2025",
    label: "Command A",
    vendor: "Cohere",
    tokenizer: "cohere",
    context: 256_000,
    inputPerM: 2.5,
    outputPerM: 10,
  },
  // ------------------------------------------------------------- Alibaba
  {
    id: "qwen3-235b",
    apiId: "qwen3-235b-a22b",
    label: "Qwen3 235B",
    vendor: "Alibaba",
    tokenizer: "qwen",
    context: 131_072,
    inputPerM: 0.22,
    outputPerM: 0.88,
    hostedRate: true,
  },
];
