/**
 * Branded PDF cost proposals.
 *
 * Generated in the browser with jsPDF. That keeps the serverless margin argument
 * intact - no render server - and means a client's prompt never leaves the
 * machine to become a PDF.
 */

// Type-only: erased at compile time, so importing it costs nothing at runtime.
// jsPDF drags in html2canvas and dompurify (~390KB raw) for its HTML renderer,
// which would otherwise land in the main chunk for every visitor who never
// exports a PDF. The real import happens inside buildProposal.
import type { jsPDF as JsPdf } from 'jspdf';
import type { Model } from './models';
import { usd, num, pct } from './format';

export interface ProposalBranding {
  /** Agency or company name in the header. Team tier can replace it entirely. */
  companyName: string;
  clientName: string;
  projectTitle: string;
  preparedBy: string;
  notes: string;
  /** Team-only: drop the "Generated by TokenTicks" footer. */
  whiteLabel: boolean;
}

export interface ProposalLine {
  model: Model;
  inputTokens: number;
  outputTokens: number;
  callsPerDay: number;
  monthlyCost: number;
  /** Monthly cost with the caching assumption applied, when one is set. */
  cachedMonthlyCost: number | null;
}

export interface ProposalInput {
  branding: ProposalBranding;
  lines: ProposalLine[];
  recommended: ProposalLine | null;
  assumptions: string[];
  pricingAsOf: string;
}

const INK = '#0b0b0b';
const MUTED = '#52514e';
const ACCENT = '#2a78d6';
const RULE = '#d9d8d2';

const MARGIN = 48;
const PAGE_W = 595; // A4 portrait at 72dpi
const PAGE_H = 842;

export async function buildProposal(input: ProposalInput): Promise<JsPdf> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = MARGIN;

  const line = (from: number, to: number, at: number, color = RULE) => {
    doc.setDrawColor(color);
    doc.setLineWidth(0.5);
    doc.line(from, at, to, at);
  };

  /** Pushes a new page when the next block would not fit. */
  const need = (space: number) => {
    if (y + space > PAGE_H - MARGIN - 28) {
      doc.addPage();
      y = MARGIN;
    }
  };

  // -------------------------------------------------------------- header --
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(INK);
  doc.text(input.branding.companyName || 'AI cost proposal', MARGIN, y);
  y += 8;
  line(MARGIN, PAGE_W - MARGIN, y, ACCENT);
  y += 22;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(input.branding.projectTitle || 'Projected LLM running costs', MARGIN, y);
  y += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(MUTED);
  const meta = [
    input.branding.clientName ? `Prepared for: ${input.branding.clientName}` : null,
    input.branding.preparedBy ? `Prepared by: ${input.branding.preparedBy}` : null,
    `Date: ${new Date().toISOString().slice(0, 10)}`,
  ].filter(Boolean) as string[];
  for (const m of meta) {
    doc.text(m, MARGIN, y);
    y += 13;
  }
  y += 10;

  // ------------------------------------------------------ recommendation --
  if (input.recommended) {
    need(84);
    doc.setFillColor('#f2f6fd');
    doc.rect(MARGIN, y - 4, PAGE_W - MARGIN * 2, 66, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(ACCENT);
    doc.text('RECOMMENDED', MARGIN + 14, y + 14);
    doc.setFontSize(15);
    doc.setTextColor(INK);
    doc.text(input.recommended.model.label, MARGIN + 14, y + 34);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(MUTED);
    const monthly = input.recommended.cachedMonthlyCost ?? input.recommended.monthlyCost;
    doc.text(
      `${usd(monthly)} per month at ${num(input.recommended.callsPerDay)} calls/day`,
      MARGIN + 14,
      y + 50,
    );
    y += 84;
  }

  // -------------------------------------------------------------- table --
  need(60);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text('Monthly cost by model', MARGIN, y);
  y += 16;

  const cols = [
    { label: 'Model', x: MARGIN, align: 'left' as const },
    { label: 'Input tok', x: MARGIN + 190, align: 'right' as const },
    { label: 'Output tok', x: MARGIN + 268, align: 'right' as const },
    { label: 'Monthly', x: MARGIN + 366, align: 'right' as const },
    { label: 'With cache', x: PAGE_W - MARGIN, align: 'right' as const },
  ];

  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  for (const c of cols) doc.text(c.label.toUpperCase(), c.x, y, { align: c.align });
  y += 6;
  line(MARGIN, PAGE_W - MARGIN, y);
  y += 14;

  doc.setFontSize(9.5);
  for (const l of input.lines) {
    need(20);
    doc.setTextColor(INK);
    doc.setFont('helvetica', l === input.recommended ? 'bold' : 'normal');
    doc.text(l.model.label, cols[0]!.x, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(MUTED);
    doc.text(num(l.inputTokens), cols[1]!.x, y, { align: 'right' });
    doc.text(num(l.outputTokens), cols[2]!.x, y, { align: 'right' });
    doc.setTextColor(INK);
    doc.text(usd(l.monthlyCost), cols[3]!.x, y, { align: 'right' });
    doc.setTextColor(l.cachedMonthlyCost === null ? MUTED : INK);
    doc.text(
      l.cachedMonthlyCost === null ? '—' : usd(l.cachedMonthlyCost),
      cols[4]!.x,
      y,
      { align: 'right' },
    );
    y += 16;
    line(MARGIN, PAGE_W - MARGIN, y - 5, '#efeeea');
  }
  y += 14;

  // --------------------------------------------------------- assumptions --
  need(70);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(INK);
  doc.text('Assumptions', MARGIN, y);
  y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(MUTED);
  for (const a of input.assumptions) {
    const wrapped = doc.splitTextToSize(`•  ${a}`, PAGE_W - MARGIN * 2);
    need(wrapped.length * 13 + 6);
    doc.text(wrapped, MARGIN, y);
    y += wrapped.length * 13 + 2;
  }
  y += 10;

  if (input.branding.notes.trim()) {
    need(60);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(INK);
    doc.text('Notes', MARGIN, y);
    y += 16;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(MUTED);
    const wrapped = doc.splitTextToSize(input.branding.notes.trim(), PAGE_W - MARGIN * 2);
    need(wrapped.length * 13);
    doc.text(wrapped, MARGIN, y);
    y += wrapped.length * 13;
  }

  // -------------------------------------------------------------- footer --
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p += 1) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setTextColor('#8b8a84');
    const footer = input.branding.whiteLabel
      ? `Rates as published ${input.pricingAsOf}. Estimates only.`
      : `Generated by TokenTicks · rates as published ${input.pricingAsOf}. Estimates only.`;
    doc.text(footer, MARGIN, PAGE_H - 28);
    doc.text(`${p} / ${pages}`, PAGE_W - MARGIN, PAGE_H - 28, { align: 'right' });
  }

  return doc;
}

export function proposalFilename(branding: ProposalBranding): string {
  const slug = (branding.projectTitle || 'llm-cost-proposal')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
  return `${slug || 'llm-cost-proposal'}-${new Date().toISOString().slice(0, 10)}.pdf`;
}

/** Percentage helper re-exported so the proposal copy matches the dashboard. */
export { pct };
