/**
 * A dated record of every model's price, kept as a starting snapshot plus a log
 * of changes, so the price of any model on any day since the record began can be
 * rebuilt - and so price-change alerts have something to compare against.
 *
 * The log is written by comparing the record's latest prices with the registry
 * as it stands (src/lib/models.data.ts), not by watching the sync. That way a
 * price that changes by any road - the daily sync, a merged review pull request,
 * a hand edit - is recorded, dated the day it was first seen here.
 *
 * Pure functions only; scripts/price-history.mjs does the reading and writing.
 */

import type { Model } from '../src/lib/models.ts';

/** The price fields that are tracked. Context windows and limits are not prices. */
export const PRICE_FIELDS = ['inputPerM', 'outputPerM', 'cacheReadPerM', 'cacheWritePerM'] as const;
export type PriceField = (typeof PRICE_FIELDS)[number];

/** USD per 1M tokens; a missing cache rate means the model publishes none. */
export type Prices = Partial<Record<PriceField, number>>;

export type PriceEvent =
  | { date: string; model: string; kind: 'added'; prices: Prices }
  | { date: string; model: string; kind: 'removed' }
  | { date: string; model: string; kind: 'price'; field: PriceField; from: number | null; to: number | null };

export interface PriceHistory {
  about: string;
  /** The day the starting snapshot was taken. */
  startedOn: string;
  baseline: Record<string, Prices>;
  /** Oldest first. */
  events: PriceEvent[];
}

const ABOUT =
  'TokenTicks model price history. baseline = every model\'s prices (USD per 1M tokens) on startedOn; ' +
  'events = every change since, oldest first. Generated by scripts/price-history.mjs.';

export function pricesOf(m: Model): Prices {
  const p: Prices = {};
  for (const f of PRICE_FIELDS) {
    const v = m[f];
    if (typeof v === 'number') p[f] = v;
  }
  return p;
}

/** Every model's prices as they stood at the end of `date` (inclusive), or today when omitted. */
export function pricesOn(h: PriceHistory, date?: string): Record<string, Prices> {
  const out: Record<string, Prices> = {};
  for (const [id, p] of Object.entries(h.baseline)) out[id] = { ...p };
  for (const e of h.events) {
    if (date !== undefined && e.date > date) break;
    if (e.kind === 'added') out[e.model] = { ...e.prices };
    else if (e.kind === 'removed') delete out[e.model];
    else {
      const p = (out[e.model] ??= {});
      if (e.to === null) delete p[e.field];
      else p[e.field] = e.to;
    }
  }
  return out;
}

/** A new record whose baseline is the registry as it stands on `date`. */
export function startHistory(models: readonly Model[], date: string): PriceHistory {
  const baseline: Record<string, Prices> = {};
  for (const m of [...models].sort((a, b) => a.id.localeCompare(b.id))) baseline[m.id] = pricesOf(m);
  return { about: ABOUT, startedOn: date, baseline, events: [] };
}

/**
 * The events that bring the record up to the registry, dated `date`. Models are
 * visited in id order and fields in PRICE_FIELDS order, so a run is deterministic.
 */
export function diffAgainst(h: PriceHistory, models: readonly Model[], date: string): PriceEvent[] {
  const known = pricesOn(h);
  const events: PriceEvent[] = [];
  const current = new Map(models.map((m) => [m.id, m]));
  const ids = [...new Set([...Object.keys(known), ...current.keys()])].sort();
  for (const id of ids) {
    const m = current.get(id);
    const before = known[id];
    if (!m) {
      events.push({ date, model: id, kind: 'removed' });
      continue;
    }
    const now = pricesOf(m);
    if (!before) {
      events.push({ date, model: id, kind: 'added', prices: now });
      continue;
    }
    for (const f of PRICE_FIELDS) {
      const from = before[f] ?? null;
      const to = now[f] ?? null;
      if (from !== to) events.push({ date, model: id, kind: 'price', field: f, from, to });
    }
  }
  return events;
}

/** The record brought up to date (a new one when there is none yet), and what changed. */
export function recordHistory(
  h: PriceHistory | null,
  models: readonly Model[],
  date: string,
): { history: PriceHistory; added: PriceEvent[] } {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error(`date is YYYY-MM-DD, got ${date}`);
  if (!h) return { history: startHistory(models, date), added: [] };
  const last = h.events.at(-1)?.date ?? h.startedOn;
  if (date < last) throw new Error(`cannot record ${date}: the history already runs to ${last}`);
  const added = diffAgainst(h, models, date);
  return { history: added.length ? { ...h, events: [...h.events, ...added] } : h, added };
}

/** Stable, diff-friendly JSON: one event per line. */
export function renderHistory(h: PriceHistory): string {
  const baseline = Object.entries(h.baseline)
    .map(([id, p]) => `    ${JSON.stringify(id)}: ${JSON.stringify(p)}`)
    .join(',\n');
  const events = h.events.map((e) => `    ${JSON.stringify(e)}`).join(',\n');
  return (
    `{\n  "about": ${JSON.stringify(h.about)},\n  "startedOn": ${JSON.stringify(h.startedOn)},\n` +
    `  "baseline": {\n${baseline}\n  },\n  "events": [${events ? `\n${events}\n  ` : ''}]\n}\n`
  );
}
